-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 0. CUSTOM TYPES (Required for functions)
-- ==========================================
DROP TYPE IF EXISTS public.leg_type CASCADE;
CREATE TYPE public.leg_type AS (
    sport text,
    league text,
    event text,
    market text,
    status text,
    odds numeric
);

-- ==========================================
-- 1. TABLES
-- ==========================================

-- Profiles (Required by App)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'usuario',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Analisis
CREATE TABLE IF NOT EXISTS public.analisis (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    partido_id INTEGER NOT NULL,
    resultado_analisis JSONB NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    api_data JSONB
);
ALTER TABLE public.analisis ENABLE ROW LEVEL SECURITY;

-- Analysis Jobs
CREATE TABLE IF NOT EXISTS public.analysis_jobs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    api_fixture_id BIGINT NOT NULL,
    fixture_id UUID,
    status TEXT NOT NULL,
    completeness_score INTEGER,
    estimated_calls INTEGER,
    actual_calls INTEGER,
    progress_jsonb JSONB,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.analysis_jobs ENABLE ROW LEVEL SECURITY;

-- Analysis Runs
CREATE TABLE IF NOT EXISTS public.analysis_runs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    job_id UUID REFERENCES public.analysis_jobs(id),
    fixture_id UUID,
    model_version TEXT,
    summary_pre_text TEXT,
    report_pre_jsonb JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);
ALTER TABLE public.analysis_runs ENABLE ROW LEVEL SECURITY;

-- API Keys
CREATE TABLE IF NOT EXISTS public.api_keys (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    provider TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    priority INTEGER,
    daily_limit INTEGER,
    used_today INTEGER DEFAULT 0,
    last_used_at TIMESTAMP WITH TIME ZONE,
    cooldown_until TIMESTAMP WITH TIME ZONE,
    last_error_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- API Request Logs
CREATE TABLE IF NOT EXISTS public.api_request_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    correlation_id TEXT,
    analysis_job_id UUID REFERENCES public.analysis_jobs(id),
    endpoint TEXT NOT NULL,
    params_jsonb JSONB,
    key_id UUID REFERENCES public.api_keys(id),
    status INTEGER,
    latency_ms INTEGER,
    error_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);
ALTER TABLE public.api_request_logs ENABLE ROW LEVEL SECURITY;

-- Apuestas (Legacy/Alternative?)
CREATE TABLE IF NOT EXISTS public.apuestas (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    date DATE NOT NULL,
    event TEXT NOT NULL,
    market TEXT NOT NULL,
    stake NUMERIC NOT NULL,
    odds NUMERIC NOT NULL,
    status TEXT NOT NULL,
    payout NUMERIC,
    image TEXT,
    legs JSONB
);
ALTER TABLE public.apuestas ENABLE ROW LEVEL SECURITY;

-- Bets (Active Table)
CREATE TABLE IF NOT EXISTS public.bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    date DATE NOT NULL,
    event TEXT NOT NULL,
    market TEXT, 
    stake NUMERIC NOT NULL,
    odds NUMERIC NOT NULL,
    status TEXT NOT NULL,
    payout NUMERIC NOT NULL,
    image TEXT
);
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;

-- Bet Legs (Relational)
CREATE TABLE IF NOT EXISTS public.bet_legs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id BIGINT REFERENCES public.bets(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    sport TEXT NOT NULL,
    league TEXT NOT NULL,
    event TEXT NOT NULL,
    market TEXT NOT NULL,
    odds NUMERIC NOT NULL,
    status TEXT NOT NULL
);
ALTER TABLE public.bet_legs ENABLE ROW LEVEL SECURITY;

-- Fixtures
CREATE TABLE IF NOT EXISTS public.fixtures (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    api_fixture_id BIGINT NOT NULL,
    league_id BIGINT,
    season INTEGER,
    date_utc TIMESTAMP WITH TIME ZONE,
    home_team_id BIGINT,
    away_team_id BIGINT,
    status TEXT,
    payload_jsonb JSONB,
    last_synced_at TIMESTAMP WITH TIME ZONE
);
ALTER TABLE public.fixtures ENABLE ROW LEVEL SECURITY;

-- Fixture Tables (Related to fixtures)
CREATE TABLE IF NOT EXISTS public.fixture_events (
    fixture_id UUID REFERENCES public.fixtures(id) NOT NULL,
    payload_jsonb JSONB,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (fixture_id)
);
ALTER TABLE public.fixture_events ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.fixture_lineups (
    fixture_id UUID REFERENCES public.fixtures(id) NOT NULL,
    payload_jsonb JSONB,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (fixture_id)
);
ALTER TABLE public.fixture_lineups ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.fixture_stats (
    fixture_id UUID REFERENCES public.fixtures(id) NOT NULL,
    payload_jsonb JSONB,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (fixture_id)
);
ALTER TABLE public.fixture_stats ENABLE ROW LEVEL SECURITY;

-- Partido Detalles Cache
CREATE TABLE IF NOT EXISTS public.partido_detalles_cache (
    fixture_id BIGINT PRIMARY KEY,
    dossier JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);
ALTER TABLE public.partido_detalles_cache ENABLE ROW LEVEL SECURITY;

-- Partidos
CREATE TABLE IF NOT EXISTS public.partidos (
    id INTEGER PRIMARY KEY,
    fecha DATE NOT NULL
);
ALTER TABLE public.partidos ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- 2. RLS POLICIES
-- ==========================================
-- NOTE: We use DROP IF EXISTS to avoid errors if re-running the script.

-- Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Bets
DROP POLICY IF EXISTS "Users can view own bets" ON public.bets;
CREATE POLICY "Users can view own bets" ON public.bets FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own bets" ON public.bets;
CREATE POLICY "Users can insert own bets" ON public.bets FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own bets" ON public.bets;
CREATE POLICY "Users can update own bets" ON public.bets FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own bets" ON public.bets;
CREATE POLICY "Users can delete own bets" ON public.bets FOR DELETE USING (auth.uid() = user_id);

-- Bet Legs
DROP POLICY IF EXISTS "Users can view own bet legs" ON public.bet_legs;
CREATE POLICY "Users can view own bet legs" ON public.bet_legs FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.bets WHERE bets.id = bet_legs.bet_id AND bets.user_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can insert own bet legs" ON public.bet_legs;
CREATE POLICY "Users can insert own bet legs" ON public.bet_legs FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.bets WHERE bets.id = bet_legs.bet_id AND bets.user_id = auth.uid())
);

-- Analysis Jobs (Authenticated)
DROP POLICY IF EXISTS "Auth users view jobs" ON public.analysis_jobs;
CREATE POLICY "Auth users view jobs" ON public.analysis_jobs FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Auth users insert jobs" ON public.analysis_jobs;
CREATE POLICY "Auth users insert jobs" ON public.analysis_jobs FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ==========================================
-- 3. STORED PROCEDURES (FUNCTIONS)
-- ==========================================

-- Function: get_my_claim
CREATE OR REPLACE FUNCTION public.get_my_claim(claim text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
  SELECT COALESCE(current_setting('request.jwt.claims', true)::jsonb ->> claim, null)::jsonb
$function$;

-- Function: handle_new_user (Trigger-based)
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$function$;

-- Trigger for handle_new_user
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Function: create_bet_with_legs (Transactional)
CREATE OR REPLACE FUNCTION public.create_bet_with_legs(p_date date, p_event text, p_market text, p_stake numeric, p_odds numeric, p_status text, p_payout numeric, p_image text, p_legs leg_type[])
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    new_bet_id bigint;
BEGIN
    -- Insertar la apuesta principal en la tabla 'bets' y obtener su ID.
    INSERT INTO public.bets (user_id, date, event, market, stake, odds, status, payout, image)
    VALUES (auth.uid(), p_date, p_event, p_market, p_stake, p_odds, p_status, p_payout, p_image)
    RETURNING id INTO new_bet_id;

    -- Si hay selecciones (legs), insertarlas en la tabla 'bet_legs'.
    IF array_length(p_legs, 1) > 0 THEN
        INSERT INTO public.bet_legs (bet_id, sport, league, event, market, status, odds)
        SELECT
            new_bet_id,
            leg.sport,
            leg.league,
            leg.event,
            leg.market,
            leg.status,
            leg.odds
        FROM unnest(p_legs) AS leg;
    END IF;

    -- Devolver el ID de la apuesta recién creada.
    RETURN new_bet_id;
END;
$function$;