import React from 'react';
import { LegalLayout } from './LegalLayout';

export const TermsOfService: React.FC = () => {
    return (
        <LegalLayout title="Terms of Service" lastUpdated="February 25, 2026">
            <h2>1. Agreement to Terms</h2>
            <p>
                By accessing or using Derbix ("the Service"), operated by Derbix ("we", "us", "our"),
                you agree to be bound by these Terms of Service. If you do not agree to these terms,
                do not use the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
                Derbix is a Software-as-a-Service (SaaS) platform that provides AI-powered sports data
                analytics and match intelligence reports for football (soccer). Our service delivers
                statistical analysis, probability assessments, and data-driven insights generated by
                artificial intelligence models.
            </p>
            <p>
                <strong>Derbix is NOT a betting platform, bookmaker, or gambling operator.</strong> We do not
                process bets, handle wagers, or facilitate gambling transactions. We provide informational
                data analytics only. Users independently decide how to apply insights at their own discretion
                and risk.
            </p>

            <h2>3. Eligibility</h2>
            <p>
                You must be at least 18 years old to use Derbix. By using our Service, you represent
                and warrant that you meet this age requirement and have the legal capacity to enter
                into these Terms.
            </p>

            <h2>4. Account Registration</h2>
            <p>
                To access certain features, you must create an account. You agree to provide accurate,
                current, and complete information during registration and to keep your account information
                updated. You are responsible for maintaining the confidentiality of your account credentials
                and for all activities that occur under your account.
            </p>

            <h2>5. Subscription Plans and Billing</h2>
            <h3>5.1 Plans</h3>
            <p>
                Derbix offers tiered subscription plans (Free, Starter, Pro, Premium) with varying levels
                of access to analytics features. Plan details, pricing, and included features are displayed
                on our pricing page and may be updated from time to time.
            </p>
            <h3>5.2 Payment</h3>
            <p>
                Paid subscriptions are billed on a recurring basis (monthly or annually) through our
                payment processor. By subscribing to a paid plan, you authorize us to charge your
                payment method at the applicable rate for your selected billing cycle.
            </p>
            <h3>5.3 Automatic Renewal</h3>
            <p>
                Subscriptions automatically renew at the end of each billing period unless cancelled
                before the renewal date. You can cancel your subscription at any time through your
                account portal.
            </p>

            <h2>6. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul>
                <li>Use the Service for any unlawful purpose or in violation of any applicable laws</li>
                <li>Resell, redistribute, or commercially exploit our analytics content without authorization</li>
                <li>Attempt to reverse-engineer, decompile, or extract our AI models or algorithms</li>
                <li>Use automated tools (bots, scrapers) to access the Service beyond normal usage</li>
                <li>Share your account credentials with third parties</li>
                <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>

            <h2>7. Intellectual Property</h2>
            <p>
                All content, data, analytics reports, AI models, branding, and software comprising
                Derbix are our exclusive property or licensed to us. You may not copy, modify,
                distribute, or create derivative works from our content without prior written consent.
            </p>

            <h2>8. Disclaimer of Warranties</h2>
            <p>
                The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind,
                whether express or implied. We do not guarantee the accuracy, completeness, or
                reliability of any analytics, predictions, or data provided through the Service.
            </p>
            <p>
                <strong>Sports analytics involve inherent uncertainty.</strong> Past performance data
                and statistical models do not guarantee future outcomes. Any decisions made based
                on our analytics are entirely at your own risk.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
                To the maximum extent permitted by law, Derbix shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages, including but not limited to
                loss of profits, data, or other intangible losses, arising from your use of or
                inability to use the Service.
            </p>
            <p>
                Our total liability for any claim arising from the Service shall not exceed the
                amount you paid us in the twelve (12) months preceding the claim.
            </p>

            <h2>10. Responsible Use</h2>
            <p>
                If you choose to use our analytics in connection with sports betting activities,
                you are solely responsible for complying with all applicable laws and regulations
                in your jurisdiction. You acknowledge that betting involves financial risk and
                should be done responsibly. Never risk more than you can afford to lose.
            </p>

            <h2>11. Termination</h2>
            <p>
                We reserve the right to suspend or terminate your account at any time if you
                violate these Terms or engage in activity that could harm the Service or other users.
                You may terminate your account at any time by cancelling your subscription and
                contacting us.
            </p>

            <h2>12. Changes to Terms</h2>
            <p>
                We may update these Terms from time to time. We will notify registered users of
                material changes via email or in-app notification. Continued use of the Service
                after changes constitutes acceptance of the revised Terms.
            </p>

            <h2>13. Governing Law</h2>
            <p>
                These Terms shall be governed by and construed in accordance with the laws of
                the Republic of Colombia. Any disputes shall be resolved through the courts of
                Bogota, Colombia.
            </p>

            <h2>14. Contact</h2>
            <p>
                For questions about these Terms, please contact us at:{' '}
                <a href="mailto:support@derbix.com">support@derbix.com</a>
            </p>
        </LegalLayout>
    );
};
